local set = vim.opt_local -- set options
set.tabstop = 2
set.softtabstop = 2
set.shiftwidth = 2
set.expandtab = true
set.autoindent = false
set.smartindent = false
set.cindent = false
set.indentexpr = ''
